environment: test

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: savvy-test.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: ingress-tls
     hosts:
       - savvy-test.local