name: Savvy Homework

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

env:
  APP_NAME: savvy-node-app

permissions:
  contents: write

jobs:
  build-node:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./node
        run: npm ci

  build-and-push-docker:
    runs-on: self-hosted
    needs: build-node

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up version
        id: version
        run: |
          echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV
          export VERSION=${{ github.run_number }}

      - name: Build Docker image
        working-directory: ./node
        run: |
          docker build \
            --build-arg IPGEOLOCATION_API_KEY=${{ secrets.IPGEOLOCATION_API_KEY }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.VERSION }} .

      - name: Push Docker image
        working-directory: ./node
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.VERSION }}

  helm-upgrade:
    runs-on: self-hosted
    needs: build-and-push-docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Helm
      #   run: |
      #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Debug environment variables
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}"
          echo "VERSION=${{ env.VERSION }}"
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}"
          
      - name: Helm upgrade
        run: |
          helm upgrade --install \
            --namespace savvy-${{ github.event.inputs.environment }} \
            --values ./kubernetes/savvy-charts/envs/${{ github.event.inputs.environment }}.yaml \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.VERSION }} \
            savvy-${{ github.event.inputs.environment }} ./kubernetes/savvy-charts

      # - name: Helm upgrade
      #   run: |
      #     helm upgrade --install --namespace savvy-prod --values ./kubernetes/savvy-charts/envs/prod.yaml --set image.repository=itaybeyder/savvy-node-app:8 savvy-prod ./kubernetes/savvy-charts