name: Savvy Homework

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod
      action:
        description: "Select the action to run"
        required: true
        default: "full"
        type: choice
        options:
          - build
          - build-and-docker
          - full

env:
  APP_NAME: savvy-node-app

permissions:
  contents: write

jobs:
  build-node:
    runs-on: self-hosted
    if: ${{ github.event.inputs.action == 'build' || github.event.inputs.action == 'build-and-docker' || github.event.inputs.action == 'full' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./node
        run: npm ci

  build-and-push-docker:
    runs-on: self-hosted
    needs: build-node
    if: ${{ github.event.inputs.action == 'build-and-docker' || github.event.inputs.action == 'full' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up version
        id: version
        run: |
          echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: ./node
        run: |
          docker build \
            --build-arg IPGEOLOCATION_API_KEY=${{ secrets.IPGEOLOCATION_API_KEY }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.run_number }} .

      - name: Push Docker image
        working-directory: ./node
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.run_number }}

  helm-upgrade:
    runs-on: self-hosted
    needs: build-and-push-docker
    if: ${{ github.event.inputs.action == 'full' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug environment variables
        run: |
          echo "APP_NAME=${{ env.APP_NAME }}"
          echo "VERSION=${{ github.run_number }}"
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}"

      - name: Helm upgrade
        run: |
          helm upgrade --install \
            --namespace savvy-${{ github.event.inputs.environment }} \
            --values ./kubernetes/savvy-charts/envs/${{ github.event.inputs.environment }}.yaml \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ github.run.number }} \
            savvy-${{ github.event.inputs.environment }} ./kubernetes/savvy-charts